### ISSUE TITLE
Version 0.0.3 fails on GitHub workflows Windows tests

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/PDF-ISO_32000_2-raku#1]
I will try to ensure the builder has its pdf requirements and report results...

I have my own copy, but where do I place it for a good build?

**Comment by dwarring** [comment]
I've set up 3os testing. Passing for me sometimes on Rakudo 2022.02 https://github.com/pdf-raku/PDF-ISO_32000_2-raku/actions/runs/12528453117/job/34991330674, but did need to rerun pass.

Haven't got Rakudo latest to pass, which get random failures installing dependencies or prove6, e.g. https://github.com/pdf-raku/PDF-ISO_32000_2-raku/actions/runs/12528453117/job/34991484746

I also have Rakudo Powershell 2022.02 installed on my Windows 11 PC at home. That works reliably for me. I'm not seeing the same failures.

**Comment by tbrowder** [comment]
On Mon, Dec 30, 2024 at 11:31 David Warring ***@***.***>
wrote:

> I've set up 3os testing. Passing for me sometimes on Rakudo 2022.02
> https://github.com/pdf-raku/PDF-ISO_32000_2-raku/actions/runs/12528453117/job/34991330674,
> but did need to rerun pass.
>

Note I (and many others I believe) have stopped using Prove6 for
testing--it is more and more problematic. Nick ***@***.***), developer of zef,
convinced me to replace Prove6 with zef in all .yml files (linux, macos,
and windows)

    run |
        zef test .
        zef install .

...and other variations including "--debug" which is helpful for figuring
out testing problems.

Haven't got Rakudo latest to pass, which get random failures installing
> dependencies or prove6, e.g.
> https://github.com/pdf-raku/PDF-ISO_32000_2-raku/actions/runs/12528453117/job/34991484746
>
> I also have Rakudo Powershell 2022.02 installed on my Windows 11 PC at
> home. That works reliably for me. I'm not seeing the same failures.
>
I haven't a Windows computer anymore, so I've just been relying on GitHub's
test. It's good to know you have success. I'll close the issue.

Happy New Year, David!

Thankfully,

-Tom

**Comment by tbrowder** [comment]
Closing. David confirmed it does work on Windows 11
